# Generated by Django 4.2.1 on 2023-06-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='product',
            new_name='content_type',
        ),
    ]
